services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=oms_bootcamp'
      - 'POSTGRES_PASSWORD=foobar'
      - 'POSTGRES_USER=foobar'
    ports:
      - '5432:5432'
