spring:
  application:
    name: bootcamp-order
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/oms_bootcamp}
    username: ${SPRING_DATASOURCE_USERNAME:foobar}
    password: ${SPRING_DATASOURCE_PASSWORD:foobar}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}
  docker:
    compose:
      enabled: false
      file: ./dependencies/compose.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://foobar:foobar@mongodb:27017/oms_bootcamp}
  flyway:
    enabled: true
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
    db:
      enabled: true
app:
  kafka:
    avro:
      bootstrap-servers: ${APP_KAFKA_AVRO_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        schema.registry.url: ${APP_KAFKA_AVRO_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}
      consumer:
        properties:
          specific.avro.reader: true
    json:
      bootstrap-servers: ${APP_KAFKA_JSON_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      order_created: order.created
      user_avro_message: avro.user
      order_avro_events: avro.order
    admin:
      topics:
        - name: order.created
          partitions: 8
          replication-factor: 1
          configs:
            cleanup.policy: delete
            retention.ms: "604800000"
            compression.type: gzip
        - name: avro.user
          partitions: 8
          replication-factor: 1
          configs:
            cleanup.policy: delete
            retention.ms: "604800000"
            compression.type: gzip
        - name: avro.order
          partitions: 8
          replication-factor: 1
          configs:
            cleanup.policy: delete
            retention.ms: "604800000"
